let sopa = [
    "UGWAQVANFISBENA",
	"CCTACPGBFPBLFLB",
	"OCERAATCOJAJZWY",
	"NTTQBNRINCWREVB",
	"TWRUETAMLQIPPDD",
	"RCAICONBJPRNHIM",
	"ALMVECSOUSGEAAA",
	"FAOORRERAFARVDC",
	"UURLAAPRHOCYIJO",
	"ESFTATTISFRDFFG",
	"RTOACOOOGLVVXSO",
	"TRSVXRBPECHINAY",
	"EOBESTIARIOVJCF",
	"DEAMBULATORIONC",
	"GYCRUCEROLWLVBB"
]

let paraules = [
	"ABOCINADO", "ARPIA", "BESTIARIO", "CIMBORRIO",
	"CONTRAFUERTE","DEAMBULATORIO", "PANTOCRATOR", "TETRAMORFOS",
	"ANFISBENA", "ARQUIVOLTA", "CABECERA", "CLAUSTRO", "CRUCERO",
	"GRIFO", "PECHINA", "TRANSEPTO"
]
